version: "3"

services:
  db:
    image: postgres:13-alpine
    container_name: "bobtheplumber-pda-db"
    restart: unless-stopped
    volumes:
      - bobtheplumber_pda_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  bobtheplumber_pda_data:
