FROM postgres:9.4

#Setup environment variables used by docker-deploy-db.sh in docker
ENV HAT_HOME=/opt/hat
ENV DATABASE=RDATABASE
ENV DBUSER=RDBUSERR
ENV DBPASS=RDBPASSR
ENV HAT_OWNER='bob@gmail.com'
ENV HAT_OWNER_ID=5974832d-2dc1-4f49-adf1-c6d8bc790274
ENV HAT_OWNER_NAME='Bob'
ENV HAT_OWNER_PASSWORD='pa55w0rd'
ENV HAT_PLATFORM=RHAT_PLATFORMR
ENV HAT_PLATFORM_ID=RHAT_PLATFORM_IDR
ENV HAT_PLATFORM_NAME=RHAT_PLATFORM_NAMER
ENV HAT_PLATFORM_PASSWORD_HASH=RHAT_PLATFORM_PASSWORD_HASHR

#Get HAT files.
RUN mkdir /opt/hat
ADD required /opt/hat

#Create DB user and pass (slightly hackish)
RUN  useradd RDBUSER
RUN echo RDBUSER:RDBPASS | chpasswd

#This will initialize the database
ADD docker-deploy-db.sh /docker-entrypoint-initdb.d/
