FROM java:jre
WORKDIR /opt/docker
ADD opt /opt
RUN ["chown", "-R", "daemon:daemon", "."]
#RUN apt-get update && apt-get -y install postgresql
USER daemon
EXPOSE 8080
ENTRYPOINT ["bin/the-hat", "-DapplicationHost=0.0.0.0"]
CMD []
