name: Staging Build

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - add-github-pipelines

env:
  RUMPEL: sandbox
  RUMPEL_ALT: latest
  RUMPEL_BUCKET: dswift-hat-sandbox-frontend-build-artifacts
  REPOSITORY: public.ecr.aws/b3s6h6d5/hat

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup 
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
          architecture: x64

      - name: Frontend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_SANDBOX_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_SANDBOX_SECRET_ACCESS_KEY }}
        run: |
          cd ./hat/app/org/hatdex/hat/phata/assets/
          aws s3 cp s3://${{ env.RUMPEL_BUCKET }}/${{ env.RUMPEL }} rumpel --recursive
          aws s3 cp s3://${{ env.RUMPEL_BUCKET }}/${{ env.RUMPEL_ALT }} alt-rumpel --recursive
          cp rumpel/*.js* js/
          cp rumpel/*.css stylesheets/
          gzip --keep --force js/*.bundle.js
          cp -r rumpel/assets/* .
          cp -r alt-rumpel/* .
          rm -r rumpel
          rm -r alt-rumpel
          cd -

      - name: Build
        run: |
          sbt -Denv=prod -Dhttp.port=8080 -Dpidfile.path=/dev/null -Dplay.server.pidfile.path=/dev/null docker:stage
          docker build -t ${{ env.REPOSITORY }}/hat:${{ github.sha }} hat/target/docker/stage

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_SHARED_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_SHARED_SECRET_ACCESS_KEY }}
        
      - name: Container Push
        run: docker push ${{ env.REPOSITORY }}/hat:${{ github.sha }}

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
