name: Trivy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * MON"

env:
  REGISTRY: dataswift/hat

jobs:
  trivy-scan:
    name: Scan
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Container - Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_DATASWIFT_USER }}
          password: ${{ secrets.DOCKERHUB_DATASWIFT_PASS }}

      - name: Container - Pull
        run: docker pull ${{ env.REGISTRY }}:${{ github.sha }}

      - name: Container - Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.REGISTRY }}:${{ github.sha }}"
          format: "template"
          template: "@/contrib/sarif.tpl"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: "trivy-results.sarif"
